// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEM.Models;

namespace TEM.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221201212216_tecgas")]
    partial class tecgas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TecGas.Models.Cli_Clientes", b =>
                {
                    b.Property<int>("CodigoClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cli_CNPJ")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cli_Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cli_Endereco")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cli_Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cli_Telefone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CodigoClienteId");

                    b.ToTable("Cli_Clientes");
                });

            modelBuilder.Entity("TecGas.Models.Ord_OrdemServicos", b =>
                {
                    b.Property<int>("Ord_OrdemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClienteCodigoClienteId")
                        .HasColumnType("int");

                    b.Property<int>("CodigoClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ord_DataAbertura")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ord_Detalhes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ord_Diagnostico")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ord_Modelo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Ord_NumeroOrdem")
                        .HasColumnType("int");

                    b.Property<string>("Ord_PecasTrocadas")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ord_Solucao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ord_ValorPeca")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ord_ValorServico")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ord_ValorTotal")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Ord_OrdemId");

                    b.HasIndex("ClienteCodigoClienteId");

                    b.ToTable("Ord_OrdemServicos");
                });

            modelBuilder.Entity("TecGas.Models.Usu_Usuarios", b =>
                {
                    b.Property<int>("Usu_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Usu_Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Usu_Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Usu_Senha")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Usu_Id");

                    b.ToTable("Usu_Usuarios");
                });

            modelBuilder.Entity("TecGas.Models.Ord_OrdemServicos", b =>
                {
                    b.HasOne("TecGas.Models.Cli_Clientes", "Cliente")
                        .WithMany("Ord_OrdemServicos")
                        .HasForeignKey("ClienteCodigoClienteId");
                });
#pragma warning restore 612, 618
        }
    }
}
